- name: Get the current working directory
  command: pwd
  register: current_directory_output
- name: Print the current working directory
  debug:
    msg: "The current working directory is: {{ current_directory_output.stdout }}"
- name: Run vcs import < .repos
  shell: vcs import < lacoro-2024-ros-workshop/.repos
  args:
    chdir: "~/{{ ws_name }}/src/"
